# -*- coding: utf-8 -*-
"""genai 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wiv83ECVVRGCf53PibjeGO4gUsn7ZN4L
"""

# Install required libraries if not present
import subprocess
import sys

try:
    import transformers
    import torch
    import accelerate
except ImportError:
    print("Installing required libraries: transformers, torch, accelerate...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "transformers", "torch", "accelerate"])

from transformers import pipeline

# Load GPT-2 model
generator = pipeline(
    "text-generation",
    model="gpt2",
    device=-1  # Change to 0 if using GPU
)

# 1. Zero-shot prompt
zero_shot_prompt = (
    "Classify the sentiment of this review as Positive or Negative:\n"
    "Review: 'The product quality is excellent!'\n"
    "Sentiment:"
)

# 2. Few-shot prompt
few_shot_prompt = """
Review: 'I loved this movie, it was fantastic.'
Sentiment: Positive

Review: 'The service was slow and disappointing.'
Sentiment: Negative

Review: 'The product quality is excellent!'
Sentiment:
"""

# 3. Chain-of-Thought prompt
cot_prompt = """
Q: A shop had 15 apples. It sold 6 and then received 10 more. How many apples does it have now?
A: Let's think step by step.
15 - 6 = 9.
9 + 10 = 19.
The answer is 19.

Q: A library had 120 books. It lent out 45 and bought 30 new books. How many books does it have now?
A: Let's think step by step.
"""

# Store prompts in a list
prompts = [
    ("Zero-shot", zero_shot_prompt),
    ("Few-shot", few_shot_prompt),
    ("Chain-of-Thought", cot_prompt)
]

# Generate output for each prompt
for name, prompt in prompts:
    output = generator(
        prompt,
        max_new_tokens=40,
        num_return_sequences=1,
        do_sample=False
    )

    print("=" * 50)
    print(name)
    print("=" * 50)
    print(output[0]["generated_text"])
    print()