# -*- coding: utf-8 -*-
"""genai 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_v2iby00ypKmT7r6IMjPAJgVy9EBohGW
"""

# Install required libraries if not present
import subprocess
import sys

try:
    import transformers
    import torch
    import accelerate
except ImportError:
    print("Installing required libraries: transformers, torch, accelerate...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "transformers", "torch", "accelerate"])

from transformers import pipeline, set_seed

# Set seed for reproducibility
set_seed(42)

# Load GPT-2 model
generator = pipeline(
    "text-generation",
    model="gpt2",
    device=-1  # Use CPU (change to 0 if using GPU)
)

# Input prompt
prompt = "Artificial Intelligence will transform the future of"

# Generate text
outputs = generator(
    prompt,
    max_new_tokens=40,
    num_return_sequences=2,
    temperature=0.8,
    top_k=50,
    top_p=0.95,
    do_sample=True
)

# Display results
for i, output in enumerate(outputs, start=1):
    print(f"\n--- Generated Text {i} ---")
    print(output["generated_text"])